version: '2'
services:
  mypostgres:
    build:
      context: postgresql
    image: mypostgres
    ports:
      - "5432:5432"
    volumes:
     - lib:/var/lib/postgresql
     - log:/var/log/postgresql
     - etc:/etc/postgresql
    container_name: database
    networks:
      - default

  appartmgr:
    build: 
      context: tomcat
    image: appartmgr
    ports:
      - "8082:8080"
    depends_on:
      - mypostgres
    container_name: appartmgr
    networks:
      - default
    links:
      - mypostgres:database

#  swagger:
#    image: swagger
#    ports:
#      - "8085:8080"
#    container_name: swagger
#    depends_on:
#      - appartmgr
#    networks:
#      - default
#    links:
#      - appartmgr:appartmgr

networks:
  default:

volumes:
  lib:
  log:
  etc:
